apiVersion: 1

datasources:
  - name: Prometheus-Lambda
    type: prometheus
    access: proxy
    url: http://prometheus-lambda:9090
    isDefault: true

  - name: Prometheus-Kappa
    type: prometheus
    access: proxy
    url: http://prometheus-kappa:9090