[agent]
  interval = "2s"

[[inputs.tail]]
  files = ["/data/metrics.csv"]
  from_beginning = true

  data_format = "csv"
  csv_header_row_count = 1
  csv_column_names = ["timestamp", "temperature", "pressure"]

[[outputs.prometheus_client]]
  listen = ":9273"